name: pull-request

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  changelog_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Run changelog-checker
        run: |
          echo "Test whether CHANGELOG.md has changed when modifying doc, examples, or src..."
          CHANGED_DIRS=$(git diff --name-only origin/$GITHUB_BASE_REF...origin/${GITHUB_HEAD_REF} | grep -E '^(doc|examples|src)/' | wc -l)
          CHANGED_CHANGELOG=$(git diff --name-only origin/$GITHUB_BASE_REF...origin/${GITHUB_HEAD_REF} CHANGELOG.md | wc -l)
          if [ $CHANGED_DIRS -gt 0 ] && [ 0 -eq $CHANGED_CHANGELOG ]; then
            echo "Error: Changes in doc, examples, or src directories require a CHANGELOG.md update"
            exit 1
          fi

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      - name: Install dependencies for development
        run: uv sync --all-extras
      - name: Build docs
        run: |
          mkdir -p public
          uv run sphinx-apidoc -f -o doc/source src
          uv run make -C doc html || exit_code=$?
          if [[ $exit_code -ne 0 ]]; then
            echo "Sphinx-build failure"
            exit 1
          else
            echo "Sphinx-build success"
            mv doc/build/html/* public
          fi
      - name: Upload docs
        uses: actions/upload-artifact@v7
        with:
          name: docs
          path: public
